<a href="https://colab.research.google.com/github/ShubhMody/Tensorflow-Developer-Certification-Prep/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we are going to cover some of the most fundamental concepts of tensor using tensorflow


More specifically,we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors&NumPy
* Using@tf.function(away to speed up your regular Python functions)
* Using GPUs with TensorFlow(or TPUS)
* Exercises to try for yourself

#Introduction to Tensors

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.8.2


In [ ]:
# Create tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check number of dimensions of a tensor

scalar.ndim

0

In [ ]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix = tf.constant([[10, 7],
                     [12, 8]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [12,  8]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
another_matrix = tf.constant([[10., 7.],
                              [11., 8.],
                              [5. , 6.]], dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [11.,  8.],
       [ 5.,  6.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# Lets craete a tensor

tensor = tf.constant([[[10, 5, 7],
                      [2, 4, 7]],

                     [[2, 10, 5],
                      [6, 9, 12]],

                     [[11, 17, 3],
                      [7, 16, 13]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[10,  5,  7],
        [ 2,  4,  7]],

       [[ 2, 10,  5],
        [ 6,  9, 12]],

       [[11, 17,  3],
        [ 7, 16, 13]]], dtype=int32)>

In [ ]:
tensor.ndim

3

###What we have created so far:
* Scalar: a single number
* Vector: a number with direction(e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers(where n can be any number,a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a
vector)


### Creating Tensors with 'tf.variable'

In [ ]:
#createing the same tensor as above using tf.Variable()
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#lets try change one of the tensor in changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [ ]:
#lets try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
#Lets try change our unchangeable tensor
unchangeable_tensor[0].assign(8)
unchangeable_tensor

AttributeError: ignored

**Note:** Rarely in practice will you need to decide whether to use tf.constant or tf. Variable to create tensors, as TensorFlow does this for you. However, if in doubt, use tf.constant and change it later if needed.

### Creating Random Tensors

In [ ]:
#Create two random but same tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape =(3,2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape =(3,2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

###Shuffle the order of elements in a tensor

In [ ]:
#shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't affect learning)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
not_shuffled.ndim

#suffle our non shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
#print(tf.random.shuffle(not_shuffled, seed = 42))
print(tf.random.shuffle(not_shuffled, seed = 42))

tf.Tensor(
[[10  7]
 [ 3  4]
 [ 2  5]], shape=(3, 2), dtype=int32)


###Other ways to make tensors

In [ ]:
#Create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Create a tensor of all zeros
tf.zeros(shape = (3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
#You can also turn numpy arrays into tensors
import numpy as np

numpy_A = np.arange(1, 25, dtype = np.int32)  #create a numopy array between 1 and 25
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape = (2,3,4))
B = tf.constant(numpy_A, shape= (4,6))
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(4, 6), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]], dtype=int32)>)